### ISSUE TITLE
ODISTARTUP coupon not applied correctly in Chargify

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#475]
ODISTARTUP coupon (using querystring https://directory.theodi.org/members/new?level=supporter&coupon=ODISTARTUP) is not being applied correctly in Xero. When user goes through to payment page no discount is applied (should be 100% discount).

**Comment by greenreveller** [comment]
see #438 - similar issue

**Comment by jordelver** [comment]
The coupon was not being set on Chargify.

This was happening because the coupon field needs to be enabled for coupons to work. The field doesn't appear on most payment pages because we have some custom CSS that removes the field from view.

I've now enabled the coupon field for
* Supporter (monthly)
* Supporter (annual)
* Corporate Supporter (annual)
* Individual Supporter

The field is not enabled for "Individual Supporter - student" because it's free anyway.

#438 wasn't similar in the end, but thanks :)

You can test this now @greenreveller.

**Comment by greenreveller** [comment]
Great - thanks @jordelver, having a look now..

**Comment by greenreveller** [comment]
@jordelver just to clarify - should the coupon field be visible only when you use a URL with a coupon at the end of it? Or is the field visible to all new sign-ups?

**Comment by jordelver** [comment]
The field will be **visible** for individuals. Coupons should work for every product except for students.

Does that help @greenreveller?

**Comment by greenreveller** [comment]
So if I want to apply the STARTUP coupon to a Supporter (monthly) for example how should I do it?

**Comment by jordelver** [comment]
Use the URL `?coupon=STARTUP`

**Comment by greenreveller** [comment]
have tried that - but not showing :/

**Comment by greenreveller** [comment]
Tested for all product types and things now working fine! Hooray! Thanks @jordelver

**Comment by jordelver** [comment]
Yay! :+1:
