### ISSUE TITLE
If we assign a voucher to each university on the pilot how can we ensure that this data is carried over into Capsule? 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#506]
As membership manager I want to be able to see all students enrolled from a particular university. 

Alternative is to use 'institution name' field from registration form as a way to track which university a student is from (this must be logged in Capsule)

Open question @jordelver - what's the best way to do this?

**Comment by greenreveller** [comment]
Could use origin field (for name of promotion) in student sign up (just like nodes)

**Comment by jordelver** [comment]
We're going to transfer the Coupon value over to Capsule so that we can filter on it. This is useful not just for students but for every type of member.

URLs for student signup will look something like this:
`https://directory.theodi.org/members/new?level=student&origin=university&coupon=ODIUCL`

* [ ] Transfer the Coupon value over to Capsule
* [ ] Test that setting the origin via the URL will propagate to Capsule

**Comment by jordelver** [comment]
As discussed yesterday @greenreveller the URLs will look something like this:

https://directory.theodi.org/members/new?level=student&origin=university&coupon=SUPERFREE

I've tested this locally and it gives the desired results.

**Comment by greenreveller** [comment]
@jordelver I just created a new STARFLEET coupon to test the student membership - can you restart the system when you have a mo so that the coupon gets registered?

**Comment by jordelver** [comment]
I've just asked Sam to restart it :+1:
