### ISSUE TITLE
Load testing for student membership registration

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#540]

**Comment by jordelver** [comment]
If we need to increase capacity because of high load, it's easy to start up another node but Sam needs to be in to do it.

**Comment by jordelver** [comment]
I'm not sure what we can test through the complete user journey. Initially I wanted to test through the whole signup but that is difficult because we redirect to 3rd parties for payment. That probably doesn't matter as long as the first page works as that will capture the user data so we can manually sort any problems later.

**Comment by jordelver** [comment]
We don't need this any more. I think we're satisfied that we can handle the load by increasing our capacity as required. Do you agree @greenreveller?

**Comment by greenreveller** [comment]
Agree
